### ISSUE TITLE
no volume plugin matched

### ISSUE THREAD

**Issue by lomori** [fstab/cifs#8]
I'm following the instructions but keep getting 
E0709 11:41:16.026163 13823 desired_state_of_world_populator.go:289] Failed to add volume "cifs" (specName: "cifs") for pod "f31d6a76-a25f-11e9-bbc6-005056bb6d71" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "cifs" err=no volume plugin matched.

The cifs script was manually copied to the directory mentioned in the document and I can confirm it is there and executable on all nodes. I'm running OpenShift Origin 3.9. Any idea why the flexVolume controller can't find the plugin?

I've also checked my configuration and volume-plugin-dir is not being defined. I guess it defaults to the subdirectory described in the document?

Regards,
Luiz

**Comment by tysen514** [comment]
Did you get this figured out? I'm having the same issue and it has me stumped.

**Comment by lomori** [comment]
Unfortunately, no, sorry...

**Comment by tysen514** [comment]
I got it! I literally stumbled onto my issue.  For the sake of anyone else who might stumble onto this...
I deployed kubernetes with kubespray.  Kubespray changes the path to the default plugin directory.  Kubernetes isn't looking for the plugin at the path specified in the plugin install directions.  If someone also happened to install kubernetes with a helper script like kubespray, check the path kubernetes is looking for storage plugins.  

For me, the default path where kubespray says volume plugins should be installed was:
 /var/lib/kubelet/volume-plugins

I hope that helps someone.

**Comment by shengzhou1216** [comment]
same issue for minikube, i used the default plugin location as mentioned in doc , but still doesn't work . somebody help
